warp-gui:
  name: ''
  size: 9
  buttons:
    pvp:
      name: ''
      Material: DIAMOND
      slot: 4
      lore:
        - 'This is first line'
        - 'Second line'
      location:
        x: 1
        y: 2
        z: 3
        world: world
    koth:
      name: ''
      Material: EMERALD
      slot: 3
      lore:
        - 'First line'
        - 'Second line'
      location:
        x: 1
        y: 2
        z: 3
        world: world